name: Bug report
description: Help Notabena become the greatest note-taking app!
title: "BUG ・ [Brief description]"
labels: [ "bug" ]
assignees: ThatFrogDev

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Notabena Bug Report form. Please fill out any fields that are applicable.
  
  - type: checkboxes
    id: terms
    attributes:
      label: "Before you start, first check the following:"
      options:
        - label: I have searched the issues and confirmed that this is not a duplicate or a known issue.
          required: true
        - label: I am on the newest version of Notabena.
          required: true

  - type: dropdown
    id: version
    attributes:
      label: "Are you facing this issue using Notabena CLI or Desktop?"
      description: "(As of now, CLI is the only possible answer)"
      options:
        - "CLI"

  - type: dropdown
    id: platform
    attributes:
      label: "What platform are you using Notabena on?"
      description: "If you are using Notabena on multiple platforms, please select the one you are facing the issue on."
      multiple: false
      options:
        - "Windows 10 or newer"
        - "Other Windows"
        - "macOS"
        - "Linux"

  - type: textarea
    id: bug-description
    attributes:
      label: "What kind of bug are you facing?"
      description: "Be concise in your description!"

  - type: textarea
    id: steps
    attributes:
      label: "How to reproduce the bug?"
      description: "Please be as detailed as possible!"
      placeholder: |
        1. Open ...
        1. Run ...
        1. Go ...
        1. See error ...
    validations:
        required: false


  - type: textarea
    id: expected-behavior
    attributes:
      label: "What did you expect that would happen?"
    validations:
      required: true
    

  - type: textarea
    id: screenshots
    attributes:
      label: "Can you send us some screenshots?"
      description: "Could you send any screenshots to help us better understand the error?"
      placeholder: |
        ![Your screenshot](https://user-images.githubusercontent.com/...)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Anything to add?"
      description: "Add any other context about the problem here."

  - type: markdown
    attributes:
      value: |
        Thanks for your time.