name: CI checks

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "stable", "rc", "dev" ]

jobs:
  check_formatting: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all -- --check
    
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features
